<?php

/**
 * @file
 * Module file for WM Custom module.
 *
 */

/**
 * Implementation of hook_webform_select_options_info().
 * See webform/webform_hooks.php for further information on this hook in the Webform API.
 */
function custom_webform_select_options_info() {
  $items = array();
    $items['node_titles'] = array(
      'title' => t('Trip titles'),
      'options callback' => 'custom_webform_pre_build_list_trip_titles'
    );
  return $items;
}
/**
 * The following piece of code is based on the trips in WM.
 *
 */ 
function custom_webform_pre_build_list_trip_titles() {
  $options = array();
  $result = db_query("SELECT nid, title FROM {node} where status=1 and type=:type ORDER BY title", array(':type' => 'trips' ));
  foreach ($result as $row) {
    $options[$row->nid] = $row->title;
  }
  return $options;
  
}

/**
 * The following piece of code is based on the trips in WM.
 *
 */ 
function custom_webform_get_node_title($nid) {
  $title="";
  $result = db_query("SELECT nid, title FROM {node} where type=:type and nid=:nid ORDER BY title", array(':type' => 'trips',':nid'=>$nid ));
  foreach ($result as $row) {
    $title = $row->title;
  }
   return $title;
}

/**
 * The Webform Deafult values.
 *
 */ 
function custom_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'webform_client_form_83' || $form_id == 'webform_client_form_352' ){
	 // print "<pre>";
	 // print_r($form['submitted']['trip_start_date']);
	if(isset($_POST['trip_type'])){
		$form['submitted']['trip_type']['#default_value'] = $_POST['trip_type'];
		}
	if(isset($_POST['select_trip'])){
		$form['submitted']['select_trip']['#default_value'] = custom_webform_get_node_title($_POST['select_trip']);
		$form['submitted']['select_trip']['#attributes'] = array('readonly' => 'readonly');;
		}
	if(isset($_POST['trip_amount'])){
		//print $_POST['trip_amount'];
		$form['submitted']['trip_cost']['#default_value'] = $_POST['trip_amount'];
		$form['submitted']['trip_amount']['#default_value'] = $_POST['trip_amount'];
		}
	if(isset($_POST['pending'])){
		$form['submitted']['trip_cost']['#default_value'] = $_POST['trip_amount'];
		if(isset($_POST['pending_amt'])){
			$form['submitted']['trip_amount']['#default_value'] = $_POST['pending_amt'];
			}
		}
	if(isset($_POST['advanced'])){
		$form['submitted']['trip_cost']['#default_value'] = $_POST['trip_amount'];
		if(isset($_POST['booking_amount'])){
			$form['submitted']['trip_amount']['#default_value'] = $_POST['booking_amount'];
			}
		}		
	if(isset($_POST['start_date'])){
		//print $_POST['start_date'];
		//$start_date=explode("-",$_POST['start_date']);
		$form['submitted']['trip_dates_fieldset']['trip_start_date']['#default_value'] = $_POST['start_date'];
		$form['submitted']['trip_dates_fieldset']['trip_end_date']['#default_value'] = $_POST['end_date'];
		//$form['submitted']['trip_dates_fieldset']['trip_end_date']['month']['#default_value'] = $end_date[1];
		//$form['submitted']['trip_dates_fieldset']['trip_end_date']['year']['#default_value'] = $end_date[2];
		}		
  } 
}

function custom_block_info() {
  $blocks['search-box-hide'] = array(
    'info' => t('Show Hide Search Box'), 
  );

 $blocks['search-box'] = array(
    'info' => t('Search Box'), 
  );
  return $blocks;
}


function custom_block_view($delta='') {
  $block = array();
  switch ($delta) {
    case 'search-box-hide':
      $block['subject'] = '';
      $block['content'] = '<form action="/trips" id="search-fixed-top">
							<div class="search_trip_box hide_fare_box">
							<div class="white-wrapper">
							<div class="search_trip_bar">
							<div class="col-md-5 noP">
							<div class="search_trip_input "><input name="title" placeholder="Search Trips by their names e.g. Everest Base Camp" type="text" /><button class="trip_search"><i class="icon-caret-down"></i></button>
							<div class="clearfix"></div>
							</div>
							</div>
							<div class="col-md-4 noP">
							<div class="trip_radio_pos">
							<div class="search_trip_radio hide_trip">
							<div class="checkboxFour"><input checked="checked" class="trip" name="rtrip" type="radio" value="1" /><span>Scheduled departures</span></div>
							<div class="checkboxFour1"><input class="trip" name="rtrip" type="radio" value="2" /><span>All trips</span></div>
							</div>
							</div>
							</div>
							<div class="col-md-3 noP">
							<div class="search_trip_btn"><button type="submit">SEARCH TRIP <i class="icon-search"></i></button></div>
							</div>
							<div class="clearfix"></div>
							</div>
							</div>
							</div>
							</form>';
      break;

    case 'search-box':
      $block['subject'] = '';
      $block['content'] = '<div class="home_searchbar">
							<div class="arrow">
							<p class="home_srtxt">or Find your adventure</p>
							<p class="arrow_one">&nbsp;</p>
							</div>
							<form action="/trips" id="search-fixed">
							<div class="search_trip_box">
							<div class="white-wrapper-search">
							<div class="search_trip_bar">
							<div class="col-md-5 noP">
							<div class="search_trip_input "><input name="title" placeholder="Search Trips by their names e.g. Everest Base Camp" type="text" /><button class="trip_search"><i class="icon-caret-down"></i></button>
							<div class="clearfix"></div>
							</div>
							</div>
							<div class="col-md-4 noP">
							<div class="trip_radio_pos">
							<div class="search_trip_radio hide_trip">
							<div class="checkboxFour"><input checked="checked" class="trip" name="rtrip" type="radio" value="1" /><span>Scheduled departures</span></div>
							<div class="checkboxFour1"><input class="trip" name="rtrip" type="radio" value="2" /><span>All trips</span></div>
							</div>
							</div>
							</div>
							<div class="col-md-3 noP">
							<div class="search_trip_btn"><button type="submit">SEARCH TRIP <i class="icon-search"></i></button></div>
							</div>
							<div class="clearfix"></div>
							</div>
							</div>
							</div>
							</form>
							</div>';
      break;

  }
  return $block;
}